/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {
  interface AppHeader {}
  interface AppHome {}
  interface AppMenu {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface BoilerPlate {}
  interface PageConfig {}
  interface PageConfigAnswers {}
  interface PageConfigQuestions {}
}

declare global {


  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {}
  var HTMLAppMenuElement: {
    prototype: HTMLAppMenuElement;
    new (): HTMLAppMenuElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLBoilerPlateElement extends Components.BoilerPlate, HTMLStencilElement {}
  var HTMLBoilerPlateElement: {
    prototype: HTMLBoilerPlateElement;
    new (): HTMLBoilerPlateElement;
  };

  interface HTMLPageConfigElement extends Components.PageConfig, HTMLStencilElement {}
  var HTMLPageConfigElement: {
    prototype: HTMLPageConfigElement;
    new (): HTMLPageConfigElement;
  };

  interface HTMLPageConfigAnswersElement extends Components.PageConfigAnswers, HTMLStencilElement {}
  var HTMLPageConfigAnswersElement: {
    prototype: HTMLPageConfigAnswersElement;
    new (): HTMLPageConfigAnswersElement;
  };

  interface HTMLPageConfigQuestionsElement extends Components.PageConfigQuestions, HTMLStencilElement {}
  var HTMLPageConfigQuestionsElement: {
    prototype: HTMLPageConfigQuestionsElement;
    new (): HTMLPageConfigQuestionsElement;
  };
  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-menu': HTMLAppMenuElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'boiler-plate': HTMLBoilerPlateElement;
    'page-config': HTMLPageConfigElement;
    'page-config-answers': HTMLPageConfigAnswersElement;
    'page-config-questions': HTMLPageConfigQuestionsElement;
  }
}

declare namespace LocalJSX {
  interface AppHeader extends JSXBase.HTMLAttributes<HTMLAppHeaderElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppMenu extends JSXBase.HTMLAttributes<HTMLAppMenuElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'match'?: MatchResults;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface BoilerPlate extends JSXBase.HTMLAttributes<HTMLBoilerPlateElement> {}
  interface PageConfig extends JSXBase.HTMLAttributes<HTMLPageConfigElement> {}
  interface PageConfigAnswers extends JSXBase.HTMLAttributes<HTMLPageConfigAnswersElement> {}
  interface PageConfigQuestions extends JSXBase.HTMLAttributes<HTMLPageConfigQuestionsElement> {}

  interface IntrinsicElements {
    'app-header': AppHeader;
    'app-home': AppHome;
    'app-menu': AppMenu;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'boiler-plate': BoilerPlate;
    'page-config': PageConfig;
    'page-config-answers': PageConfigAnswers;
    'page-config-questions': PageConfigQuestions;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


